spring:
  datasource:
    url: jdbc:mysql://localhost:3306/relink?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
        order_updates: true
        order_inserts: true
        show_sql: true

  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: always    # Spring Batch ?? ??? ?? ??
